"""unique rate type+effective_date

Revision ID: 1dd5441d68a1
Revises: 92c0fb6fb117
Create Date: 2026-08-30 16:52:08.896248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd5441d68a1'
down_revision: Union[str, Sequence[str], None] = '92c0fb6fb117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rate_type_date', 'rate_configs', ['type', 'effective_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rate_type_date', 'rate_configs', type_='unique')
    # ### end Alembic commands ###
