"""init schema

Revision ID: 92c0fb6fb117
Revises:
Create Date: 2026-08-30 11:52:16.229195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92c0fb6fb117"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "staff", "tenant", name="role_enum"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index(
        op.f("ix_audit_logs_log_id"), "audit_logs", ["log_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "rate_configs",
        sa.Column("rate_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("water", "electric", name="rate_type_enum"), nullable=False
        ),
        sa.Column("rate_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("rate_id"),
    )
    op.create_index(
        op.f("ix_rate_configs_created_by"), "rate_configs", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_rate_configs_rate_id"), "rate_configs", ["rate_id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("current_address", sa.Text(), nullable=True),
        sa.Column("national_id_encrypted", sa.String(length=255), nullable=True),
        sa.Column("emergency_contact", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_index(
        op.f("ix_tenants_tenant_id"), "tenants", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_tenants_user_id"), "tenants", ["user_id"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("rent", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "security_deposit", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("contract_file_url", sa.String(length=500), nullable=True),
        sa.Column("special_conditions", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "active", "expired", "terminated", name="contract_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    op.create_index(
        op.f("ix_contracts_contract_id"), "contracts", ["contract_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_created_by"), "contracts", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_room_id"), "contracts", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_tenant_id"), "contracts", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_documents",
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(
        op.f("ix_tenant_documents_doc_id"), "tenant_documents", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_documents_tenant_id"),
        "tenant_documents",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_documents_uploaded_by"),
        "tenant_documents",
        ["uploaded_by"],
        unique=False,
    )
    op.create_table(
        "contract_checklists",
        sa.Column("cc_id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("check-in", "check-out", name="checklist_type_enum"),
            nullable=False,
        ),
        sa.Column("checklist_items", sa.JSON(), nullable=True),
        sa.Column("tenant_signature", sa.String(length=500), nullable=True),
        sa.Column("photo_urls", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.contract_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("cc_id"),
    )
    op.create_index(
        op.f("ix_contract_checklists_cc_id"),
        "contract_checklists",
        ["cc_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_checklists_contract_id"),
        "contract_checklists",
        ["contract_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_checklists_created_by"),
        "contract_checklists",
        ["created_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contract_checklists_created_by"), table_name="contract_checklists"
    )
    op.drop_index(
        op.f("ix_contract_checklists_contract_id"), table_name="contract_checklists"
    )
    op.drop_index(
        op.f("ix_contract_checklists_cc_id"), table_name="contract_checklists"
    )
    op.drop_table("contract_checklists")
    op.drop_index(
        op.f("ix_tenant_documents_uploaded_by"), table_name="tenant_documents"
    )
    op.drop_index(op.f("ix_tenant_documents_tenant_id"), table_name="tenant_documents")
    op.drop_index(op.f("ix_tenant_documents_doc_id"), table_name="tenant_documents")
    op.drop_table("tenant_documents")
    op.drop_index(op.f("ix_contracts_tenant_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_room_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_created_by"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contract_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_tenants_user_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_tenant_id"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_rate_configs_rate_id"), table_name="rate_configs")
    op.drop_index(op.f("ix_rate_configs_created_by"), table_name="rate_configs")
    op.drop_table("rate_configs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_log_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # drop enum types ที่ create_table สร้างไว้ (ไม่งั้น upgrade ซ้ำจะเจอ "type already exists")
    for _enum in (
        "checklist_type_enum",
        "rate_type_enum",
        "contract_status_enum",
        "role_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
