"""contract requests + checklist item cost

Revision ID: b1c330f21e71
Revises: 1dd5441d68a1
Create Date: 2026-08-30 19:31:10.925271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1c330f21e71"
down_revision: Union[str, Sequence[str], None] = "1dd5441d68a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_requests",
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("renew", "terminate", name="request_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                "completed",
                name="request_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("tenant_note", sa.Text(), nullable=False),
        sa.Column("preferred_date", sa.Date(), nullable=True),
        sa.Column("staff_note", sa.Text(), nullable=True),
        sa.Column("damage_total", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("handled_by", sa.Integer(), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.contract_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["handled_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_contract_requests_contract_id"),
        "contract_requests",
        ["contract_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_requests_created_by"),
        "contract_requests",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_requests_handled_by"),
        "contract_requests",
        ["handled_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_requests_request_id"),
        "contract_requests",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contract_requests_request_id"), table_name="contract_requests"
    )
    op.drop_index(
        op.f("ix_contract_requests_handled_by"), table_name="contract_requests"
    )
    op.drop_index(
        op.f("ix_contract_requests_created_by"), table_name="contract_requests"
    )
    op.drop_index(
        op.f("ix_contract_requests_contract_id"), table_name="contract_requests"
    )
    op.drop_table("contract_requests")
    # ### end Alembic commands ###
    sa.Enum(name="request_status_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="request_type_enum").drop(op.get_bind(), checkfirst=True)
