"""init add all talbe

Revision ID: 1b8b4a01b2d4
Revises: 
Create Date: 2026-07-19 18:24:17.166993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8b4a01b2d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('rateConfig',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_index(op.f('ix_rateConfig_rate_id'), 'rateConfig', ['rate_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('current_address', sa.String(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('emergency_contact', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    op.create_table('contracts',
    sa.Column('contracts_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=False),
    sa.Column('special_conditions', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('contracts_id')
    )
    op.create_index(op.f('ix_contracts_contracts_id'), 'contracts', ['contracts_id'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('tenant_documents',
    sa.Column('tenant_document_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_document_id')
    )
    op.create_index(op.f('ix_tenant_documents_tenant_document_id'), 'tenant_documents', ['tenant_document_id'], unique=False)
    op.create_index(op.f('ix_tenant_documents_tenant_id'), 'tenant_documents', ['tenant_id'], unique=False)
    op.create_table('contract_checklist',
    sa.Column('cc_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checklist_items', sa.String(), nullable=False),
    sa.Column('tenant_signature', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('update_at', sa.Date(), nullable=False),
    sa.Column('contracts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contracts_id'], ['contracts.contracts_id'], ),
    sa.PrimaryKeyConstraint('cc_id')
    )
    op.create_index(op.f('ix_contract_checklist_cc_id'), 'contract_checklist', ['cc_id'], unique=False)
    op.create_index(op.f('ix_contract_checklist_contracts_id'), 'contract_checklist', ['contracts_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_checklist_contracts_id'), table_name='contract_checklist')
    op.drop_index(op.f('ix_contract_checklist_cc_id'), table_name='contract_checklist')
    op.drop_table('contract_checklist')
    op.drop_index(op.f('ix_tenant_documents_tenant_id'), table_name='tenant_documents')
    op.drop_index(op.f('ix_tenant_documents_tenant_document_id'), table_name='tenant_documents')
    op.drop_table('tenant_documents')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_rateConfig_rate_id'), table_name='rateConfig')
    op.drop_table('rateConfig')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
